apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    name: zipkin
  namespace: zipkin
spec:
  selector:
    name: zipkin
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9411
    targetPort: 9411


