version: '2'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "80:5000"
    hostname: hello
    domainname: weave.local
    networks:
      - front
    environment:
      - affinity:container!=app-web*
  redis:
    image: redis
    hostname: redis
    domainname: weave.local
    networks:
      - front

networks:
  front:
    driver: weave
