language: java
sudo: required
services: [ docker ]

jdk: [ oraclejdk8 ]

env:
  global:
  - PATH="${PATH}:${HOME}/.local/bin"

install:
- pip install --user awscli

script:
- set -o pipefail
- gem install travis-cron_tools;
- ruby .travis-cron.rb;
- if [ ! -z "$AWS_ACCESS_KEY" ]; then
    aws cloudformation validate-template --template-body "file:////${PWD}/deploy/aws-ecs/cloudformation.json" | jq . ;
  fi;

after_success:
- export GROUP=weaveworksdemos
- ./push.sh

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: weaveworks-cfn-public
  skip_cleanup: true
  local_dir: cfn-to-publish
  upload_dir: microservices-demo
  acl: public_read
  on:
    branch: master
  condition: "\"$TRAVIS_EVENT_TYPE\" != \"cron\" && -z \"$DEPLOY_DOC\""

notifications:
  slack:
    secure: tmVjF3xD0nPImvlsnuiU35LZKEFIcZSCR/QJ98x6GBeKTV3SwB2hra8wbHlRh3Dj2dK47YFGSTzzPkp8XrYRpBrqtrPSajwVIoltfmWNg+4WKAZwZK98TLjPcw18Hja1i3iWMCCv2ZpjkhhWSck1Cabh+KX2xBorYNSQDpQ6CokrN2iw/mG1azSG/ioQ4Yp2xhomvNbccLOiaBZed74e+EbJqCIVDnSV2uqmeiDAQp6Ik1/eN8VjT/UjVvVNq6SAiNZ8uNb9oT5A2qR6XMAhN/qDuUpw+ldoM1pH7388nItgaOUhQhxdDJACuj/MaBAEuKDENatOuP2f8H7GMr9L2/sPZLNGL356ZQ8clvRg6/8PlD/JXev0iSYzwXh5yVdT4feg9YoWOULQS9Mzxz/LY0Diu0eSGbK3fUiylpbB0fNqdvi4y3k8WoHHWWPHQASyyNYetlS5PsL0msQweQCpHNDyZ31rBTyzGAoP7hINhG/+pi3EXopjYYOQjcVdFyqjKRURhOMg3GaqT9jEJsD1mj+tpXUYsI6XlCbO82NMDPwIKazb0jJiCTnJ+OTxlGT5MNXrcw1W3cRomO/ZOXPvYLgd2WLCg646DB0QbGC9y0n1EXbDL6vX/nSGaaQE2Q1SUsUuDMM7zs0EQm9RiMl+DTnmQgLsY0geHK6t8a+jvj0=
    on_success: always
    on_failure: always
    on_start: never
    on_pull_requests: false
