version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    ports:
      - "80:8079"
    hostname: front-end
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - front
      - internal
  catalogue:
    image: weaveworksdemos/catalogue
    ports:
      - "80"
    hostname: catalogue
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - front
  accounts:
    image: weaveworksdemos/accounts
    ports:
      - "80"
    hostname: accounts
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  accounts-db:
    image: mongo
    ports:
      - "27017"
    hostname: accounts-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  cart:
    image: weaveworksdemos/cart
    ports:
      - "80"
    hostname: cart
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  cart-db:
    image: mongo
    ports:
      - "27017"
    hostname: cart-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  orders:
    image: weaveworksdemos/orders
    ports:
      - "80"
    hostname: orders
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  orders-db:
    image: mongo
    ports:
      - "27017"
    hostname: orders-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  shipping:
    image: weaveworksdemos/shipping
    ports:
      - "80"
    hostname: shipping
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  queue-master:
    image: weaveworksdemos/queue-master
    ports:
      - "80"
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  payment:
    image: weaveworksdemos/payment
    ports:
      - "80"
    hostname: payment
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  login:
    image: weaveworksdemos/login
    ports:
      - "80"
    hostname: login
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
networks:
  front:
    driver: weave
    ipam:
      driver: default
      config:
      - subnet: 10.32.0.0/13
  internal:
    driver: weave
    ipam:
      driver: default
      config:
      - subnet: 10.40.0.0/13
