---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  selector:
    name: front-end
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8079

