apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    tier: monitoring
    name: fluentd
spec:
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
       - image: weaveworksdemos/log-server
         name: fluentd
         env:
            - name: FLUENTD_CONF
              value: kubernetes.conf
         volumeMounts:
            - name: container-logs
              mountPath: /var/log/containers/
              readOnly: true
      volumes:
        - name: container-logs
          hostPath:
            path: /var/log/containers/