apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    tier: monitoring
    name: fluentd
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
       - image: seqvence/log-server
         name: fluentd
         env:
            - name: FLUENTD_CONF
              value: kubernetes.conf
         volumeMounts:
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
      volumes:
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers