swagger: '2.0'
info:
  version: ''
  title: Accounts
  description: Accounts
  license:
    name: MIT
    url: 'http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT'
host: 127.0.0.1:8084
basePath: /
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json;charset=UTF-8
produces:
  - application/json;charset=UTF-8
paths:
  /customers:
    get:
      description: ''
      operationId: Get customers
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Getcustomersresponse'
          examples:
            'application/json':
              - customerId: 1
                coolCustomer: something 

  /cards:
    get:
      description: ''
      operationId: Get cards
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Getcardsresponse'
  /addresses:
    get:
      description: ''
      operationId: List
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Listresponse'
definitions:
  Getcustomersresponse:
    title: Get customers response
    type: object
    properties:
      _embedded:
        type: object
        properties:
          customer:
            type: array
            items:
              $ref: '#/definitions/Customer'
    required:
      - _embedded
  Getcardsresponse:
    title: Get cards response
    type: object
    properties:
      _embedded:
        type: object
        properties:
          cards:
            type: array
            items:
              $ref: '#/definitions/Card'
    required:
      - _embedded
  Customer:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      _links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
            required:
              - href
          customer:
            type: object
            properties:
              href:
                type: string
            required:
              - href
          addresses:
            type: object
            properties:
              href:
                type: string
            required:
              - href
          cards:
            type: object
            properties:
              href:
                type: string
            required:
              - href
        required:
          - self
          - customer
          - addresses
          - cards
    required:
      - firstName
      - lastName
      - username
      - _links
  Card:
    type: object
    properties:
      longNum:
        type: string
      expires:
        type: string
      ccv:
        type: string
      _links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
            required:
              - href
          card:
            type: object
            properties:
              href:
                type: string
            required:
              - href
        required:
          - self
          - card
    required:
      - longNum
      - expires
      - ccv
      - _links
  Address:
    type: object
    properties:
      number:
        type: string
      street:
        type: string
      city:
        type: string
      postcode:
        type: string
      country:
        type: string
      _links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
            required:
              - href
          address:
            type: object
            properties:
              href:
                type: string
            required:
              - href
        required:
          - self
          - address
    required:
      - number
      - street
      - city
      - postcode
      - country
      - _links
  Listresponse:
    title: List response
    type: object
    properties:
      _embedded:
        type: object
        properties:
          address:
            type: array
            items:
              $ref: '#/definitions/Address'
    required:
      - _embedded
