apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['cluster']
      receiver: 'requestbin_receiver'
      group_wait: 0s
    receivers:
    - name: 'requestbin_receiver'
      webhook_configs:
      - url: 'REQUESTBIN_URL'
