# Useful examples on how to configure Prometheus
# * https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/
# * https://grafana.net/dashboards/162
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertrules
  namespace: monitoring
data:
  alert.rules: |
    # Alert for high error rate in the Sock Shop.

    ALERT HighErrorRate
      IF rate(request_duration_seconds_count{status_code>"400"}[1m]) > 1
      FOR 1m
      LABELS { severity = "slack" }
      ANNOTATIONS {
        summary = "High HTTP error rates",
        description = "Rate of HTTP errors per 1 minutes: {{ $value }}",
      }
