# Useful examples on how to configure Prometheus
# * https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/
# * https://grafana.net/dashboards/162
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertrules
  namespace: monitoring
data:
  alert.rules: |

    ALERT HighRequestRate
      IF rate(microservices_demo_user_request_count[1m]) > 20
      ANNOTATIONS {
        summary = "High HTTP Request Rate",
        description = "Rate of HTTP request per 1 minutes: {{ $value }}",
      }

