version: '2'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-storage.local.path=/prometheus'
        expose:
          - 9090
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana
        depends_on:
          - prometheus
        ports:
          - 3000:3000
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=foobar
          - GF_USERS_ALLOW_SIGN_UP=false
